# Librerias

In [1]:
import pandas as pd
import sweetviz as sv

# Cargamos datos

In [2]:
# Cargar el archivo CSV
df_comentarios = pd.read_csv('../01_data/comentarios_atrapalo.csv', delimiter=",", header=0)
df_comentarios

,fecha,nota_total,grupo_de,calidad_del_espectáculo,puesta_en_escena,interpretación_artística,nombre_show,nombre_local
0,2023-10-10,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
1,2023-08-17,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
2,2023-10-13,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
3,2023-08-17,9.1,Pareja,10.0,10.0,7.5,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
4,2023-10-09,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
...,...,...,...,...,...,...,...,...
174601,2023-02-02,10.0,Solo,10.0,10.0,10.0,Histericas,Estupenda Bar
174602,2023-01-30,7.5,Amigos,7.5,7.5,7.5,Histericas,Estupenda Bar
174603,2022-11-22,10.0,Amigos,10.0,10.0,10.0,Histericas,Estupenda Bar
174604,2023-10-02,5.0,Amigos,5.0,5.0,5.0,Histericas,Estupenda Bar
174605,2023-08-21,2.5,Pareja,2.5,2.5,2.5,Histericas,Estupenda Bar

In [3]:
# Cargar el archivo CSV
df_beer1 = pd.read_csv('../01_data/comentarios_YO NUNCA SHOW,  de Raúl Massana.csv', delimiter=",", header=0)
df_beer2 = pd.read_csv('../01_data/comentarios_Quique_Matilla__Vastante_vien.csv', delimiter=",", header=0)

# Unimos archivos

In [4]:
df_beer = pd.concat([df_beer1, df_beer2], ignore_index=True)
df_beer

,fecha,nota_total,grupo_de,calidad_del_espectáculo,puesta_en_escena,interpretación_artística,nombre_show,nombre_local
0,2023-10-01,10.0,Amigos,10.0,10.0,10.0,Ignatius Farray presenta nuevo show STAND-UP C...,Beer Station - Sala 1
1,2023-09-24,10.0,Amigos,10.0,10.0,10.0,Ignatius Farray presenta nuevo show STAND-UP C...,Beer Station - Sala 1
2,2023-09-11,10.0,Amigos,10.0,10.0,10.0,Ignatius Farray presenta nuevo show STAND-UP C...,Beer Station - Sala 1
3,2023-10-06,10.0,Solo,10.0,10.0,10.0,Ignatius Farray presenta nuevo show STAND-UP C...,Beer Station - Sala 1
4,2023-10-05,10.0,Solo,10.0,10.0,10.0,Ignatius Farray presenta nuevo show STAND-UP C...,Beer Station - Sala 1
...,...,...,...,...,...,...,...,...
2986,2021-05-12,10.0,Pareja,10.0,10.0,10.0,Vaquero,Beer Station - Sala 1
2987,2023-05-22,10.0,Pareja,10.0,10.0,10.0,Pringer: a los que das a la izquierda,Beer Station - Sala 1
2988,2023-10-02,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1
2989,2023-05-28,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1
2990,2023-07-13,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1

In [5]:
df_comentarios_final = pd.concat([df_comentarios, df_beer], ignore_index=True)
df_comentarios_final

,fecha,nota_total,grupo_de,calidad_del_espectáculo,puesta_en_escena,interpretación_artística,nombre_show,nombre_local
0,2023-10-10,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
1,2023-08-17,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
2,2023-10-13,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
3,2023-08-17,9.1,Pareja,10.0,10.0,7.5,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
4,2023-10-09,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
...,...,...,...,...,...,...,...,...
177592,2021-05-12,10.0,Pareja,10.0,10.0,10.0,Vaquero,Beer Station - Sala 1
177593,2023-05-22,10.0,Pareja,10.0,10.0,10.0,Pringer: a los que das a la izquierda,Beer Station - Sala 1
177594,2023-10-02,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1
177595,2023-05-28,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1
177596,2023-07-13,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1

# Eliminamos los datos que al final no vamos a usar

In [9]:
chocita_rows = df_comentarios_final[df_comentarios_final['nombre_local'].str.contains('Chocita', case=False)]
chocita_rows

,fecha,nota_total,grupo_de,calidad_del_espectáculo,puesta_en_escena,interpretación_artística,nombre_show,nombre_local
137863,2023-04-23,10.0,Pareja,10.0,10.0,10.0,Ruben Garcia The Plan,Teatro Chocita del Loro - Gran Vía
137864,2023-05-14,9.1,Pareja,10.0,7.5,10.0,Ruben Garcia The Plan,Teatro Chocita del Loro - Gran Vía
137865,2023-02-19,10.0,Pareja,10.0,10.0,10.0,Ruben Garcia The Plan,Teatro Chocita del Loro - Gran Vía
137866,2022-12-10,10.0,Pareja,10.0,10.0,10.0,Ruben Garcia The Plan,Teatro Chocita del Loro - Gran Vía
137867,2022-12-10,10.0,Amigos,10.0,10.0,10.0,Ruben Garcia The Plan,Teatro Chocita del Loro - Gran Vía
...,...,...,...,...,...,...,...,...
159421,2022-09-25,10.0,Pareja,10.0,10.0,10.0,Ruben Garcia Haters,Teatro Chocita del Loro - Gran Vía
159422,2021-12-26,9.1,Family,7.5,10.0,10.0,Ruben Garcia Haters,Teatro Chocita del Loro - Gran Vía
159423,2021-12-27,10.0,Amigos,10.0,10.0,10.0,Ruben Garcia Haters,Teatro Chocita del Loro - Gran Vía
159424,2022-03-14,7.5,Solo,7.5,5.0,10.0,Ruben Garcia Haters,Teatro Chocita del Loro - Gran Vía
159425,2022-09-24,2.5,Pareja,0.0,0.0,7.5,Ruben Garcia Haters,Teatro Chocita del Loro - Gran Vía

In [10]:
df_comentarios_final = df_comentarios_final[df_comentarios_final['nombre_local'] != 'Teatro Chocita del Loro - Gran Vía']
df_comentarios_final

,fecha,nota_total,grupo_de,calidad_del_espectáculo,puesta_en_escena,interpretación_artística,nombre_show,nombre_local
0,2023-10-10,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
1,2023-08-17,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
2,2023-10-13,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
3,2023-08-17,9.1,Pareja,10.0,10.0,7.5,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
4,2023-10-09,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
...,...,...,...,...,...,...,...,...
177592,2021-05-12,10.0,Pareja,10.0,10.0,10.0,Vaquero,Beer Station - Sala 1
177593,2023-05-22,10.0,Pareja,10.0,10.0,10.0,Pringer: a los que das a la izquierda,Beer Station - Sala 1
177594,2023-10-02,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1
177595,2023-05-28,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1
177596,2023-07-13,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1

# Guardamos BBDD final

In [12]:
# Guardo el DataFrame en un archivo CSV
df_comentarios_final.to_csv('../01_data/total_comentarios.csv', index=False)

In [13]:
df_tipo_show = pd.read_csv('../01_data/shows_atrapalo.csv', delimiter=",", header=0)

In [14]:
# Unir los DataFrames usando 'nombre_show' como clave de unión
df_final = pd.merge(df_comentarios_final, df_tipo_show[['nombre_show', 'tipo_show']], on='nombre_show', how='left')

# Llenar los valores nulos con 'show'
df_final['tipo_show'].fillna('show', inplace=True)
df_final

,fecha,nota_total,grupo_de,calidad_del_espectáculo,puesta_en_escena,interpretación_artística,nombre_show,nombre_local,tipo_show
0,2023-10-10,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club,show
1,2023-08-17,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club,show
2,2023-10-13,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club,show
3,2023-08-17,9.1,Pareja,10.0,10.0,7.5,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club,show
4,2023-10-09,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club,show
...,...,...,...,...,...,...,...,...,...
175770,2021-05-12,10.0,Pareja,10.0,10.0,10.0,Vaquero,Beer Station - Sala 1,show
175771,2023-05-22,10.0,Pareja,10.0,10.0,10.0,Pringer: a los que das a la izquierda,Beer Station - Sala 1,show
175772,2023-10-02,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1,show
175773,2023-05-28,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1,show
175774,2023-07-13,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1,show

In [16]:
# Convertir las columnas 'nombre_show' a minúsculas en ambos DataFrames
df_comentarios_final['nombre_show'] = df_comentarios_final['nombre_show'].str.lower()
df_tipo_show['nombre_show'] = df_tipo_show['nombre_show'].str.lower()

# Unir los DataFrames usando 'nombre_show' como clave de unión
df_final = pd.merge(df_comentarios_final, df_tipo_show[['nombre_show', 'tipo_show']], on='nombre_show', how='left')

# Llenar los valores nulos con 'show'
df_final['tipo_show'].fillna('show', inplace=True)
df_final

C:\Users\STF\AppData\Local\Temp\ipykernel_10748\2322145635.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_comentarios_final['nombre_show'] = df_comentarios_final['nombre_show'].str.lower()

,fecha,nota_total,grupo_de,calidad_del_espectáculo,puesta_en_escena,interpretación_artística,nombre_show,nombre_local,tipo_show
0,2023-10-10,10.0,Pareja,10.0,10.0,10.0,los monologos de el golfo comedy club en madrid,El Golfo Comedy Club,show
1,2023-08-17,10.0,Amigos,10.0,10.0,10.0,los monologos de el golfo comedy club en madrid,El Golfo Comedy Club,show
2,2023-10-13,10.0,Pareja,10.0,10.0,10.0,los monologos de el golfo comedy club en madrid,El Golfo Comedy Club,show
3,2023-08-17,9.1,Pareja,10.0,10.0,7.5,los monologos de el golfo comedy club en madrid,El Golfo Comedy Club,show
4,2023-10-09,10.0,Amigos,10.0,10.0,10.0,los monologos de el golfo comedy club en madrid,El Golfo Comedy Club,show
...,...,...,...,...,...,...,...,...,...
175778,2021-05-12,10.0,Pareja,10.0,10.0,10.0,vaquero,Beer Station - Sala 1,show
175779,2023-05-22,10.0,Pareja,10.0,10.0,10.0,pringer: a los que das a la izquierda,Beer Station - Sala 1,show
175780,2023-10-02,10.0,Pareja,10.0,10.0,10.0,quique matilla - vastante vien,Beer Station - Sala 1,show
175781,2023-05-28,10.0,Pareja,10.0,10.0,10.0,quique matilla - vastante vien,Beer Station - Sala 1,show
175782,2023-07-13,10.0,Pareja,10.0,10.0,10.0,quique matilla - vastante vien,Beer Station - Sala 1,show

# Procedemos al EDA

In [15]:
report = sv.analyze(df_final)
report.show_html()

                                             |                                             | [  0%]   00:00 ->…

C:\Users\STF\anaconda3\envs\proyecto_final\Lib\site-packages\sweetviz\from_profiling_pandas.py:65: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(keys):
C:\Users\STF\anaconda3\envs\proyecto_final\Lib\site-packages\sweetviz\from_profiling_pandas.py:65: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(keys):
C:\Users\STF\anaconda3\envs\proyecto_final\Lib\site-packages\sweetviz\from_profiling_pandas.py:65: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(keys):
C:\Users\STF\anaconda3\envs\proyecto_final\Lib\site-packages\sweetviz\from_profiling_pandas.py:65: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(keys):
C:\Users\STF\anaconda3\envs\proyecto_final\Lib\site-packages\sweetviz\from_profiling_pandas.py:65: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(keys):

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.