In [1]:
import pandas as pd

In [3]:
df_cuentas_locales

,nombre_show,tipo_show,precio,duracion,local,nota_atrapalo,numero_opiniones
0,Los Monólogos de El Golfo Comedy Club en Madrid,cuenta_local,5.0,95.0,El Golfo Comedy Club,8.9,1656.0
1,Noches de Comedia - Monólogos en Madrid,cuenta_local,6.0,75.0,El Sombrerero Comedy Club,9.5,901.0
2,Los Monólogos del Teatro de las Aguas,cuenta_local,5.0,60.0,Teatro de las Aguas,9.5,885.0
3,"Comedy Nights, monólogos en Beer Station",cuenta_local,8.0,80.0,Beer Station,9.0,778.0
4,Los Monólogos de Estupenda Café Bar,cuenta_local,2.4,80.0,Estupenda Bar,9.0,214.0
5,Monólogos de humor - Chocita del Loro Gran vía,cuenta_local,15.0,90.0,Teatro Chocita del Loro - Gran Vía,8.8,14386.0
6,Los Monólogos de Clandestino Café-Teatro Gran vía,cuenta_local,8.0,60.0,Clandestino Café Teatro,8.4,71.0
7,Estación Comedy,cuenta_local,2.5,60.0,Estación Malasaña,8.6,137.0
8,Monólogos en San Sebastián de los Reyes,cuenta_local,6.5,75.0,La Nota Rock,NaN,NaN

In [4]:
df_cuentas_locales['local'] = df_cuentas_locales['local'].replace('Beer Station', 'Beer Station - Sala 1')
df_cuentas_locales

,nombre_show,tipo_show,precio,duracion,local,nota_atrapalo,numero_opiniones
0,Los Monólogos de El Golfo Comedy Club en Madrid,cuenta_local,5.0,95.0,El Golfo Comedy Club,8.9,1656.0
1,Noches de Comedia - Monólogos en Madrid,cuenta_local,6.0,75.0,El Sombrerero Comedy Club,9.5,901.0
2,Los Monólogos del Teatro de las Aguas,cuenta_local,5.0,60.0,Teatro de las Aguas,9.5,885.0
3,"Comedy Nights, monólogos en Beer Station",cuenta_local,8.0,80.0,Beer Station - Sala 1,9.0,778.0
4,Los Monólogos de Estupenda Café Bar,cuenta_local,2.4,80.0,Estupenda Bar,9.0,214.0
5,Monólogos de humor - Chocita del Loro Gran vía,cuenta_local,15.0,90.0,Teatro Chocita del Loro - Gran Vía,8.8,14386.0
6,Los Monólogos de Clandestino Café-Teatro Gran vía,cuenta_local,8.0,60.0,Clandestino Café Teatro,8.4,71.0
7,Estación Comedy,cuenta_local,2.5,60.0,Estación Malasaña,8.6,137.0
8,Monólogos en San Sebastián de los Reyes,cuenta_local,6.5,75.0,La Nota Rock,NaN,NaN

In [5]:
df_tipo_show = pd.concat([df_cuentas_shows, df_cuentas_locales], ignore_index=True)
df_tipo_show

,nombre_show,tipo_show,precio,duracion,local,nota_atrapalo,numero_opiniones
0,Monólogos en la Chocita del Loro Carabanchel,show,10.0,80.0,Teatro Chocita del Loro - Carabanchel,8.9,5208.0
1,Ladys Night en Beer Station,show,11.0,70.0,Beer Station,9.4,89.0
2,El Dojo Comedia,open_mic,8.0,70.0,El Golfo Comedy Club,9.6,150.0
3,Chic Comedy - Monólogos,open_mic,3.5,80.0,Estupenda Bar,9.0,194.0
4,Punch Comedy English.- Stand up Comedy in English,open_mic,7.0,90.0,El Golfo Comedy Club,9.3,26.0
...,...,...,...,...,...,...,...
224,Los Monólogos de Estupenda Café Bar,cuenta_local,2.4,80.0,Estupenda Bar,9.0,214.0
225,Monólogos de humor - Chocita del Loro Gran vía,cuenta_local,15.0,90.0,Teatro Chocita del Loro - Gran Vía,8.8,14386.0
226,Los Monólogos de Clandestino Café-Teatro Gran vía,cuenta_local,8.0,60.0,Clandestino Café Teatro,8.4,71.0
227,Estación Comedy,cuenta_local,2.5,60.0,Estación Malasaña,8.6,137.0
228,Monólogos en San Sebastián de los Reyes,cuenta_local,6.5,75.0,La Nota Rock,NaN,NaN

In [6]:
df_comentarios_final

,fecha,nota_total,grupo_de,calidad_del_espectáculo,puesta_en_escena,interpretación_artística,nombre_show,nombre_local
0,2023-10-10,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
1,2023-08-17,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
2,2023-10-13,10.0,Pareja,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
3,2023-08-17,9.1,Pareja,10.0,10.0,7.5,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
4,2023-10-09,10.0,Amigos,10.0,10.0,10.0,Los Monologos De El Golfo Comedy Club En Madrid,El Golfo Comedy Club
...,...,...,...,...,...,...,...,...
175745,2021-05-12,10.0,Pareja,10.0,10.0,10.0,Vaquero,Beer Station - Sala 1
175746,2023-05-22,10.0,Pareja,10.0,10.0,10.0,Pringer: a los que das a la izquierda,Beer Station - Sala 1
175747,2023-10-02,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1
175748,2023-05-28,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1
175749,2023-07-13,10.0,Pareja,10.0,10.0,10.0,Quique Matilla - Vastante vien,Beer Station - Sala 1

In [10]:
# Convertir los nombres a minúsculas para evitar problemas de mayúsculas y minúsculas
df_comentarios_final['nombre_show'] = df_comentarios_final['nombre_show'].str.lower()
df_tipo_show['nombre_show'] = df_tipo_show['nombre_show'].str.lower()

# Obtener los nombres únicos de cada DataFrame
nombres_comentarios_final = set(df_comentarios_final['nombre_show'].unique())
nombres_tipo_show = set(df_tipo_show['nombre_show'].unique())

# Encontrar los nombres de shows que están en ambos DataFrames
nombres_comunes = nombres_comentarios_final.intersection(nombres_tipo_show)

# Imprimir los nombres comunes
print("Nombres de shows comunes entre df_comentarios_final y df_tipo_show:")
for nombre in nombres_comunes:
    print(nombre)

Nombres de shows comunes entre df_comentarios_final y df_tipo_show:
kalderas - stand up comedy
el micro abierto de la estupenda
bhonny lorenzo presenta bonifacetico
comedy rally
yo nunca show,  de raúl massana
dos de cal
mangos y papayas
open beer - open mic de stand-up comedy
hardcore - patricia galván
comedy nights, monólogos en beer station
humor de perros
nene, ¡que me jodan! , un monólogo muy jodido
isabel rey - diva de barrio, un show de comedia
jaja party - presentado por javi durán
luis álvaro - el espectáculo
quique matilla - vastante vien
ladys night en beer station
probando material
gente bien
el ahorcado open mic
sparks- el show de humor negro - silvia sparks
stand up en el momento
el humor de los 90s hoy
el dojo comedia
carmen romero y bianca kovacs - odio a la gente podcast
mierda fresca open - stand-up comedy presentado por richard salamanca